# Build Stage
FROM golang:1.24 AS build
WORKDIR /app

# Copiar mod e sum
COPY go.mod go.sum ./
RUN go mod download

# Copiar todo o projeto
COPY . .

# Build do binário — IMPORTANTE: caminho correto do main!
RUN go build -o server ./cmd/api/main.go

# Runtime
FROM gcr.io/distroless/base-debian12
WORKDIR /app

COPY --from=build /app/server /app/server

ENV PORT=8080
EXPOSE 8080

USER nonroot:nonroot

CMD ["/app/server"]
